### ISSUE TITLE
Custom style

### ISSUE THREAD

**Issue by hmontes** [mathdroid/react-360-gaze-button#1]
You can allow custom style in your gaze button. Simply change

```
<View onEnter={this.handleEnter} onExit={this.handleExit}>
```

to

```
<View onEnter={this.handleEnter} onExit={this.handleExit} {...this.props}>
```

so. I can use.

```
<GazeButton style={{transform: [translate: [x,y,z]}}>
....
</GazeButton
```

I can do a pull request later if you want

**Comment by mathdroid** [comment]
You're right. We should pass down extra props 👍 

Pull request is always welcome :)

**Comment by mathdroid** [comment]
By the way, @hmontes . What use case can't you do by styling the child component instead of the `GazeButton`?

**Comment by iiidefektiii** [comment]
I'm trying out you're gaze code. Everything works but I always get NaN for remainingTime so it never launches the handleClick() any ideas?

**Comment by mathdroid** [comment]
Hi there @iiidefektiii . Would you mind opening a new issue and also show me your how you implement the component? :)

**Comment by iiidefektiii** [comment]
my bad. delete those. I was rushing and posted under here instead of a new issue. I posted a new issue.

**Comment by mathdroid** [comment]
Custom style is supported in v1.0.x 😇
