### ISSUE TITLE
Errors with v 2.0.0 of React-vr

### ISSUE THREAD

**Issue by jgwinner** [mathdroid/react-360-gaze-button#2]
Hi

I have a (running) project on React-VR 2.0.0

I just installed react-vr-gaze-button via npm (with --save).

I got a lot of errors about duplicates on running. When I refreshed my working VR world, even without adding any gaze buttons, I got the following error:

"Ambiguous resolution: module 'F:\\ReactVR\\Foo\\index.vr.js' tries to require 'react-vr', but there are several files providing this module. You can delete or fix them: \n\nF:\\ReactVR\\Foo\\node_modules\\react-vr-gaze-button\\node_modules\\react-vr\\package.json\n\nF:\\ReactVR\\Foo\\node_modules\\react-vr\\package.json",

**Comment by jgwinner** [comment]
It looks like react-vr-gaze-button is marked to work ONLY with version 1.4.0 ... I think all you'd have to do is change the package requirements?

**Comment by mathdroid** [comment]
Thanks for the issue @jgwinner.

My mistake was to include `react` and `react-vr` in the `dependencies`. I've updated that in `v0.1.4` and it now works in `react-vr@2.0.0`. 

Make sure to remove the `node_modules` before installing the new version. 👍

**Comment by jgwinner** [comment]
That was quick! Thank you

**Comment by jgwinner** [comment]
BTW: I found out, npm cache clear --force doesn't work. You have to RESET the cache.

I delete the entire node_modules directory and it still kept referring to the gaze button ... bizarre!
