### ISSUE TITLE
Not able to see the white raycaster

### ISSUE THREAD

**Issue by Rhut-virani** [mathdroid/react-360-gaze-button#6]
Gaze button works fine and its getting clicked and styled also but i am not able to see the raycaster aim dot.

Am i Missing something here?

**Comment by mathdroid** [comment]
What raycaster are you using?

- [ ] Make sure a raycaster is present (checkout https://github.com/mathdroid/simple-raycaster)
- [ ] Make sure at least a `Surface` is present

**Comment by etabrizi** [comment]
Can the raycaster work without a surface? instead a 3D location with an entity to gaze at?

**Comment by Manny-Mobfish** [comment]
@etabrizi  I'm using the raycaster with a 3D location. We positioned Planes instead of entity's, but I think it will also work with entity's

**Comment by Rhut-virani** [comment]
It was me not knowing how to clearly use it but it works flawlessly.
thanks
