### ISSUE TITLE
Warning: Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by amittbhardwj** [mathdroid/react-360-gaze-button#7]
I am getting this warning. How to solve this?
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the GazeButton component.
  | reactConsoleErrorHandler | @ | ExceptionsManager.js:73
-- | -- | -- | --
  | printWarning | @ | warning.js:35
  | warning | @ | warning.js:59
  | warnAboutUpdateOnUnmounted | @ | ReactNativeFiber-dev.js:2438
  | scheduleUpdateImpl | @ | ReactNativeFiber-dev.js:2765
  | scheduleUpdate | @ | ReactNativeFiber-dev.js:2751
  | enqueueSetState | @ | ReactNativeFiber-dev.js:1569
  | ReactComponent.setState | @ | react.development.js:218
  | GazeButton._this.step | @ | index.js:93
  | _callTimer | @ | JSTimers.js:150
  | callTimers | @ | JSTimers.js:405
  | __callFunction | @ | MessageQueue.js:306
  | (anonymous) | @ | MessageQueue.js:108
  | __guard | @ | MessageQueue.js:269
  | MessageQueue.callFunctionReturnFlushedQueue | @ | MessageQueue.js:107

**Comment by mathdroid** [comment]
Sorry for the late response. Have you found the solution? I'll take a look at this later today.

**Comment by amittbhardwj** [comment]
Thanks for the reply. I wasn't able to solve this issue.
